version: '3.8'

services:
  telegram-bot:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - REMOVEBG_API_KEY=${REMOVEBG_API_KEY}
      - PHOTOROOM_API_KEY=${PHOTOROOM_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET:-fallback-secret}
      - WEBHOOK_MODE=false  # Use polling in local development
      - PORT=5000
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  telegram-bot-webhook:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - REMOVEBG_API_KEY=${REMOVEBG_API_KEY}
      - PHOTOROOM_API_KEY=${PHOTOROOM_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET:-fallback-secret}
      - WEBHOOK_MODE=true
      - RENDER_EXTERNAL_URL=${WEBHOOK_URL}
      - PORT=5000
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    profiles:
      - webhook

networks:
  default:
    name: telegram-bot-network